sudo: required

services:
    - docker

before_install:
    - cp .env.test.dist .env
    - docker-compose up -d
    - docker-compose exec web composer install --no-interaction
    - docker-compose exec web php bin/console doctrine:schema:update --force
    - docker-compose exec web php bin/console hautelook:fixtures:load -q --purge-with-truncate

script:
    - docker-compose exec web php bin/phpunit